language: python
dist: focal

git:
  depth: 1

jobs:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: 3.9
    - python: pypy3
    - name: "latest deps"
      python: 3.9
      env: UPGRADE="pip install --upgrade trio wsproto"

install:
  - pip install -r requirements-dev.txt
  - $UPGRADE
  - pip install -e .

script:
  - make test
  - make lint

after_success:
  - make coverage
